In [7]:
import numpy as np

my_array = np.arange(1000000)
my_list = list(range(1000000))

%timeit my_list2 = [i * 2 for i in my_list]
%timeit my_array2 = my_array * 2

68.9 ms ± 9.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.35 ms ± 406 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
a = [[1, 1.2, 3], [-1, -2, -3]]
data = np.array(a)
print(data)
print('-')

# 0차원: 스칼라(scala), 1차원: 벡터(vector), 2차원: 메트릭스(matrix), 3차원 이상: 텐서(tenser)
print(data * 10)
print(data + data)
print('-')

print(data.shape)
print(data.dtype)
print('-')

[[ 1.   1.2  3. ]
 [-1.  -2.  -3. ]]
-
[[ 10.  12.  30.]
 [-10. -20. -30.]]
[[ 2.   2.4  6. ]
 [-2.  -4.  -6. ]]
-
(2, 3)
float64
-


## ndarray 생성하기

In [26]:
import numpy as np

data1 = [1,2,3,4,5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))
print('-')

arr2 = np.array([[1.1,2.2], [3.3,4.4]])
print(arr2)
print(type(arr2))
print('-')

print(arr1.ndim)
print(arr2.ndim)
print('-')

print(arr1.shape)
print(arr2.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
-
[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>
-
1
2
-
(5,)
(2, 2)


In [33]:
print(np.zeros(10))
print([0] * 10)

print(np.zeros((5,5)))
# 메모리 안에 남아있는 값들이 있을 때 0 대신 그 값들이 들어갈 수도 있다.
print(np.empty((2,2,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [34]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [39]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [42]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1.dtype)
float_arr = arr1.astype(np.float64)
print(float_arr)
print(float_arr.dtype)
print('-')

arr2 = np.array([1.1, 2.2, 3.3])
print(arr2)
print(arr2.dtype)
int_arr = arr2.astype(np.int64)
print(int_arr)
print(int_arr.dtype)

[1 2 3]
int64
[1. 2. 3.]
float64
-
[1.1 2.2 3.3]
float64
[1 2 3]
int64


## 산술 연산

In [52]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr * arr)
print(arr + arr)
print(1 / arr)
print(arr ** 3)
print(arr - arr)
print('-')

arr1 = np.array([[3,2,1], [6,5,4]])
print(arr, arr1)
print(arr > arr1)
print(arr == 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]
[[0 0 0]
 [0 0 0]]
-
[[1 2 3]
 [4 5 6]] [[3 2 1]
 [6 5 4]]
[[False False  True]
 [False False  True]]
[[False False  True]
 [False False False]]


## 색인과 슬라이싱

In [55]:
import numpy as np
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[2:5])
print('-')

arr[2:5] = 10
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[2 3 4]
-
[ 0  1 10 10 10  5  6  7  8  9]


In [56]:
py_list = [1,2,3,4,5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [61]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

print(arr[1][1])
print(arr[1,1])

[[1 2 3]
 [4 5 6]]
5
5


In [64]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]], 
                 [[10, 11, 12], [13,14,15], [16,17,18]], 
                [[19, 20, 21], [22,23,24], [25,26,27]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [72]:
arr3d = np.array([[[1,2,3], [4,5,6], [7,8,9]], 
                 [[10, 11, 12], [13,14,15], [16,17,18]], 
                [[19, 20, 21], [22,23,24], [25,26,27]]])
print(arr3d[2][0][1])
print(arr3d[2,0,1])

# 인덱스 접근은 안으로 들어가는 것이기 때문에 대괄호가 하나 줄어든다.
print(arr3d[:1, 1:, 2:])
print(arr3d[0, 1:, 2:])

arr3d[:1, 1:, 2:] = 9999
print(arr3d)

20
20
[[[6]
  [9]]]
[[6]
 [9]]
[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  10   11   12]
  [  13   14   15]
  [  16   17   18]]

 [[  19   20   21]
  [  22   23   24]
  [  25   26   27]]]


## 불리언 값으로 선택

In [83]:
import numpy as np

names= np.array(['hwang', 'hong', 'hwang', 'hong'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

print(names == 'hwang')
print(data[names == 'hwang'])
print('-')

print(data[names == 'hwang', 0])
print(data[names == 'hwang', :1])
print('-')

print(names != 'hwang')
print(~(names == 'hwang'))

[ True False  True False]
[['math' '60']
 ['eng' '70']]
-
['math' 'eng']
[['math']
 ['eng']]
-
[False  True False  True]
[False  True False  True]


In [85]:
cond = names == 'hwang'
print(data[cond])

[['math' '60']
 ['eng' '70']]


## 팬시 색인 (fancy indexing)

In [92]:
import numpy as np

arr = np.zeros((8,4))
print(arr)
print('-')

for i in range(8):
    arr[i] = i
print(arr)
print('-')

# 원하는 인덱스에서 있는 값들을 뽑아올 수 있다
print(arr[[4,3,2,1]])
print('-')
print(arr[[-3,-2, -5]])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
-
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]
-
[[5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [3. 3. 3. 3.]]


In [102]:
arr = np.arange(0, 32).reshape(8, 4)
print(arr)
print('-')
print(arr[[1, 5], [2, 3]])
print(arr[[1, 5]][:, [2, 3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
-
[ 6 23]
[[ 6  7]
 [22 23]]


## 배열 전치

In [106]:
arr = np.arange(15).reshape(3, 5)
print(arr)
print('-')
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [109]:
# 행렬의 내적, 곱
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [275]:
samples = np.random.standard_normal(size = (3,3))
print(samples)

[[-0.36799524 -0.21408068  0.24890472]
 [-0.8374264   0.27330969 -0.46977861]
 [ 0.38032956 -0.82478234  1.26882593]]


In [276]:
# nan은 결측치
arr = np.sqrt(samples)
print(arr)
print('-')

arr1 = np.abs(samples)
print(arr1)
print('-')

print(np.isnan(arr))
print(np.isnan(arr1))

[[       nan        nan 0.49890352]
 [       nan 0.52279029        nan]
 [0.61670865        nan 1.12642174]]
[[0.36799524 0.21408068 0.24890472]
 [0.8374264  0.27330969 0.46977861]
 [0.38032956 0.82478234 1.26882593]]
[[ True  True False]
 [ True False  True]
 [False  True False]]
[[False False False]
 [False False False]
 [False False False]]


C:\Users\seong\AppData\Local\Temp\ipykernel_27196\1901053778.py:2: RuntimeWarning: invalid value encountered in sqrt
  arr = np.sqrt(samples)
